from decimal import Decimal

# Electronics & Appliances / Home Appliances
HOME_APPLIANCES_PRODUCTS = [
    {'product_id': 'PK-1027', 'name': 'Dawlance Inverter AC 1.5T', 'sku': 'DWAC15', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 5, 'reorder_level': 2, 'reorder_qty': 5, 'cost_price': Decimal('95000.00'), 'unit_price': Decimal('118000.00'), 'supplier': 'Dawlance', 'brand': 'Dawlance', 'status': 'Active'},
    {'product_id': 'PK-1028', 'name': 'Haier Inverter AC 1T', 'sku': 'HAAC1', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 5, 'reorder_level': 2, 'reorder_qty': 5, 'cost_price': Decimal('75000.00'), 'unit_price': Decimal('94000.00'), 'supplier': 'Haier Pakistan', 'brand': 'Haier', 'status': 'Active'},
    {'product_id': 'PK-1029', 'name': 'Orient AC 1.5T', 'sku': 'ORAC15', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 5, 'reorder_level': 2, 'reorder_qty': 5, 'cost_price': Decimal('80000.00'), 'unit_price': Decimal('99000.00'), 'supplier': 'Orient Electronics', 'brand': 'Orient', 'status': 'Active'},
    {'product_id': 'PK-1030', 'name': 'Dawlance Refrigerator 12CF', 'sku': 'DWREF12', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 4, 'reorder_level': 1, 'reorder_qty': 4, 'cost_price': Decimal('65000.00'), 'unit_price': Decimal('80000.00'), 'supplier': 'Dawlance', 'brand': 'Dawlance', 'status': 'Active'},
    {'product_id': 'PK-1031', 'name': 'Haier Fridge 14CF', 'sku': 'HAFR14', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 4, 'reorder_level': 1, 'reorder_qty': 4, 'cost_price': Decimal('72000.00'), 'unit_price': Decimal('90000.00'), 'supplier': 'Haier Pakistan', 'brand': 'Haier', 'status': 'Active'},
    {'product_id': 'PK-1032', 'name': 'PEL Refrigerator 16CF', 'sku': 'PELRF16', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 4, 'reorder_level': 1, 'reorder_qty': 4, 'cost_price': Decimal('82000.00'), 'unit_price': Decimal('102000.00'), 'supplier': 'PEL Pakistan', 'brand': 'PEL', 'status': 'Active'},
    {'product_id': 'PK-1033', 'name': 'Dawlance Washing Machine', 'sku': 'DWWM', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 5, 'reorder_level': 2, 'reorder_qty': 5, 'cost_price': Decimal('45000.00'), 'unit_price': Decimal('56000.00'), 'supplier': 'Dawlance', 'brand': 'Dawlance', 'status': 'Active'},
    {'product_id': 'PK-1034', 'name': 'Haier Front Load 8kg', 'sku': 'HAFL8', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 4, 'reorder_level': 1, 'reorder_qty': 4, 'cost_price': Decimal('75000.00'), 'unit_price': Decimal('95000.00'), 'supplier': 'Haier Pakistan', 'brand': 'Haier', 'status': 'Active'},
    {'product_id': 'PK-1035', 'name': 'National Microwave 30L', 'sku': 'NATMW', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 8, 'reorder_level': 3, 'reorder_qty': 8, 'cost_price': Decimal('22000.00'), 'unit_price': Decimal('28000.00'), 'supplier': 'National', 'brand': 'National', 'status': 'Active'},
    {'product_id': 'PK-1036', 'name': 'Kenwood Blender', 'sku': 'KENBL', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Home Appliances', 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('3500.00'), 'unit_price': Decimal('5000.00'), 'supplier': 'Kenwood Pakistan', 'brand': 'Kenwood', 'status': 'Active'},
]
