from decimal import Decimal

# Electronics & Appliances / Laptops & Computers
LAPTOPS_AND_COMPUTERS_PRODUCTS = [
    {'product_id': 'PK-1011', 'name': 'Dell Inspiron 15', 'sku': 'DELI15', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('115000.00'), 'unit_price': Decimal('139000.00'), 'supplier': 'Dell Pakistan', 'brand': 'Dell', 'status': 'Active'},
    {'product_id': 'PK-1012', 'name': 'HP Pavilion 14', 'sku': 'HPP14', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('108000.00'), 'unit_price': Decimal('130000.00'), 'supplier': 'HP Distributors', 'brand': 'HP', 'status': 'Active'},
    {'product_id': 'PK-1013', 'name': 'Lenovo IdeaPad 3', 'sku': 'LENIP3', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('95000.00'), 'unit_price': Decimal('115000.00'), 'supplier': 'Lenovo Pakistan', 'brand': 'Lenovo', 'status': 'Active'},
    {'product_id': 'PK-1014', 'name': 'Asus VivoBook 15', 'sku': 'ASVB15', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('105000.00'), 'unit_price': Decimal('128000.00'), 'supplier': 'Asus Pakistan', 'brand': 'Asus', 'status': 'Active'},
    {'product_id': 'PK-1015', 'name': 'Dell Latitude 5520', 'sku': 'DELL5520', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 3, 'reorder_level': 1, 'reorder_qty': 3, 'cost_price': Decimal('175000.00'), 'unit_price': Decimal('210000.00'), 'supplier': 'Dell Pakistan', 'brand': 'Dell', 'status': 'Active'},
    {'product_id': 'PK-1016', 'name': 'HP ProBook 450', 'sku': 'HPPB450', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 3, 'reorder_level': 1, 'reorder_qty': 3, 'cost_price': Decimal('155000.00'), 'unit_price': Decimal('185000.00'), 'supplier': 'HP Distributors', 'brand': 'HP', 'status': 'Active'},
    {'product_id': 'PK-1017', 'name': 'Apple MacBook Air M2', 'sku': 'MBAIM2', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 3, 'reorder_level': 1, 'reorder_qty': 3, 'cost_price': Decimal('290000.00'), 'unit_price': Decimal('339000.00'), 'supplier': 'iWorld Pakistan', 'brand': 'Apple', 'status': 'Active'},
    {'product_id': 'PK-1018', 'name': 'Acer Aspire 7', 'sku': 'ACRA7', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Laptops & Computers', 'stock_quantity': 8, 'reorder_level': 2, 'reorder_qty': 8, 'cost_price': Decimal('120000.00'), 'unit_price': Decimal('145000.00'), 'supplier': 'Acer Pakistan', 'brand': 'Acer', 'status': 'Active'},
]
