from decimal import Decimal

# Electronics & Appliances / Mobile Phones
MOBILE_PHONES_PRODUCTS = [
    {'product_id': 'PK-1001', 'name': 'Samsung Galaxy A54', 'sku': 'SMA54', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 10, 'reorder_level': 1, 'reorder_qty': 10, 'cost_price': Decimal('75000.00'), 'unit_price': Decimal('95000.00'), 'supplier': 'TechHub Pvt Ltd', 'brand': 'Samsung', 'status': 'Active'},
    {'product_id': 'PK-1002', 'name': 'Samsung Galaxy A34', 'sku': 'SMA34', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 10, 'reorder_level': 2, 'reorder_qty': 10, 'cost_price': Decimal('55000.00'), 'unit_price': Decimal('68000.00'), 'supplier': 'TechHub Pvt Ltd', 'brand': 'Samsung', 'status': 'Active'},
    {'product_id': 'PK-1003', 'name': 'iPhone 14', 'sku': 'IPH14', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('240000.00'), 'unit_price': Decimal('279000.00'), 'supplier': 'iWorld Pakistan', 'brand': 'Apple', 'status': 'Active'},
    {'product_id': 'PK-1004', 'name': 'iPhone 13', 'sku': 'IPH13', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('185000.00'), 'unit_price': Decimal('215000.00'), 'supplier': 'iWorld Pakistan', 'brand': 'Apple', 'status': 'Active'},
    {'product_id': 'PK-1005', 'name': 'Vivo Y36', 'sku': 'VIVY36', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 15, 'reorder_level': 3, 'reorder_qty': 15, 'cost_price': Decimal('42000.00'), 'unit_price': Decimal('52000.00'), 'supplier': 'Vivo Pakistan', 'brand': 'Vivo', 'status': 'Active'},
    {'product_id': 'PK-1006', 'name': 'Vivo V27', 'sku': 'VIVV27', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 10, 'reorder_level': 2, 'reorder_qty': 10, 'cost_price': Decimal('65000.00'), 'unit_price': Decimal('80000.00'), 'supplier': 'Vivo Pakistan', 'brand': 'Vivo', 'status': 'Active'},
    {'product_id': 'PK-1007', 'name': 'Oppo A78', 'sku': 'OPPA78', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 15, 'reorder_level': 3, 'reorder_qty': 15, 'cost_price': Decimal('38000.00'), 'unit_price': Decimal('47000.00'), 'supplier': 'Oppo Distributors', 'brand': 'Oppo', 'status': 'Active'},
    {'product_id': 'PK-1008', 'name': 'Oppo Reno10', 'sku': 'OPPR10', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 8, 'reorder_level': 1, 'reorder_qty': 8, 'cost_price': Decimal('82000.00'), 'unit_price': Decimal('99000.00'), 'supplier': 'Oppo Distributors', 'brand': 'Oppo', 'status': 'Active'},
    {'product_id': 'PK-1009', 'name': 'Realme 11 Pro', 'sku': 'RLM11P', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 15, 'reorder_level': 3, 'reorder_qty': 15, 'cost_price': Decimal('52000.00'), 'unit_price': Decimal('65000.00'), 'supplier': 'Realme Pakistan', 'brand': 'Realme', 'status': 'Active'},
    {'product_id': 'PK-1010', 'name': 'Xiaomi Redmi 12', 'sku': 'XMR12', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Mobile Phones', 'stock_quantity': 20, 'reorder_level': 4, 'reorder_qty': 20, 'cost_price': Decimal('34000.00'), 'unit_price': Decimal('42000.00'), 'supplier': 'Xiaomi Pakistan', 'brand': 'Xiaomi', 'status': 'Active'},
]
