from decimal import Decimal

# Electronics & Appliances / Televisions
TELEVISIONS_PRODUCTS = [
    {'product_id': 'PK-1019', 'name': 'Samsung 43" 4K Smart TV', 'sku': 'SMTV43', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('78000.00'), 'unit_price': Decimal('98000.00'), 'supplier': 'TechHub Pvt Ltd', 'brand': 'Samsung', 'status': 'Active'},
    {'product_id': 'PK-1020', 'name': 'Samsung 55" QLED', 'sku': 'SMTV55', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 3, 'reorder_level': 1, 'reorder_qty': 3, 'cost_price': Decimal('150000.00'), 'unit_price': Decimal('185000.00'), 'supplier': 'TechHub Pvt Ltd', 'brand': 'Samsung', 'status': 'Active'},
    {'product_id': 'PK-1021', 'name': 'TCL 40" Smart TV', 'sku': 'TCL40', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 8, 'reorder_level': 2, 'reorder_qty': 8, 'cost_price': Decimal('42000.00'), 'unit_price': Decimal('52000.00'), 'supplier': 'TCL Pakistan', 'brand': 'TCL', 'status': 'Active'},
    {'product_id': 'PK-1022', 'name': 'TCL 50" 4K TV', 'sku': 'TCL50', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 5, 'reorder_level': 1, 'reorder_qty': 5, 'cost_price': Decimal('68000.00'), 'unit_price': Decimal('85000.00'), 'supplier': 'TCL Pakistan', 'brand': 'TCL', 'status': 'Active'},
    {'product_id': 'PK-1023', 'name': 'Haier 32" LED', 'sku': 'HAI32', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 10, 'reorder_level': 3, 'reorder_qty': 10, 'cost_price': Decimal('28000.00'), 'unit_price': Decimal('36000.00'), 'supplier': 'Haier Pakistan', 'brand': 'Haier', 'status': 'Active'},
    {'product_id': 'PK-1024', 'name': 'Haier 43" Smart TV', 'sku': 'HAI43', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 8, 'reorder_level': 2, 'reorder_qty': 8, 'cost_price': Decimal('55000.00'), 'unit_price': Decimal('68000.00'), 'supplier': 'Haier Pakistan', 'brand': 'Haier', 'status': 'Active'},
    {'product_id': 'PK-1025', 'name': 'LG 55" OLED', 'sku': 'LGOLED55', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 3, 'reorder_level': 1, 'reorder_qty': 3, 'cost_price': Decimal('195000.00'), 'unit_price': Decimal('239000.00'), 'supplier': 'LG Pakistan', 'brand': 'LG', 'status': 'Active'},
    {'product_id': 'PK-1026', 'name': 'Sony Bravia 50"', 'sku': 'SONY50', 'unit': 'Unit', 'category': 'Electronics & Appliances', 'subcategory': 'Televisions', 'stock_quantity': 3, 'reorder_level': 1, 'reorder_qty': 3, 'cost_price': Decimal('125000.00'), 'unit_price': Decimal('155000.00'), 'supplier': 'Sony Pakistan', 'brand': 'Sony', 'status': 'Active'},
]
