# Generated by Django 4.2.7 on 2026-06-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_erpuser_password_erpuser_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions_count',
        ),
    ]
