# Generated by Django 4.2.7 on 2026-06-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
