# Generated by Django 4.2.7 on 2026-06-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_erpuser_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='requires_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
