# Generated by Django 4.2.7 on 2026-06-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_role_permissions_count'),
        ('user_management', '0006_erpuser_requires_password_change'),
    ]

    operations = [
    ]
