# Generated by Django 4.2.7 on 2026-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_merge_20260620_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpuser',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
