version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - CORS_ALLOW_ALL_ORIGINS=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend

  frontend:
    build:
      context: ./bizionary-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./bizionary-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/
    depends_on:
      - backend
