from decimal import Decimal

# Pharmaceuticals & Health / OTC Medicines
OTC_MEDICINES_PRODUCTS = [
    {'product_id': 'PK-1144', 'name': 'Panadol Extra 20tabs', 'sku': 'PNDLEX20', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 150, 'reorder_level': 30, 'reorder_qty': 150, 'cost_price': Decimal('85.00'), 'unit_price': Decimal('120.00'), 'supplier': 'GSK Pakistan', 'brand': 'Panadol', 'status': 'Active'},
    {'product_id': 'PK-1145', 'name': 'Panadol CF 10tabs', 'sku': 'PNDLCF10', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 150, 'reorder_level': 30, 'reorder_qty': 150, 'cost_price': Decimal('70.00'), 'unit_price': Decimal('100.00'), 'supplier': 'GSK Pakistan', 'brand': 'Panadol', 'status': 'Active'},
    {'product_id': 'PK-1146', 'name': 'Brufen 400mg 10tabs', 'sku': 'BRFN400', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 150, 'reorder_level': 30, 'reorder_qty': 150, 'cost_price': Decimal('95.00'), 'unit_price': Decimal('135.00'), 'supplier': 'Abbott Pakistan', 'brand': 'Brufen', 'status': 'Active'},
    {'product_id': 'PK-1147', 'name': 'Disprin 10tabs', 'sku': 'DSPRN10', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 150, 'reorder_level': 30, 'reorder_qty': 150, 'cost_price': Decimal('45.00'), 'unit_price': Decimal('70.00'), 'supplier': 'Reckitt Pakistan', 'brand': 'Disprin', 'status': 'Active'},
    {'product_id': 'PK-1148', 'name': 'ORS Sachets x10', 'sku': 'ORSSCHT', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 150, 'reorder_level': 30, 'reorder_qty': 150, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('175.00'), 'supplier': 'Otsuka Pakistan', 'brand': 'ORS', 'status': 'Active'},
    {'product_id': 'PK-1149', 'name': 'Vitamin C 500mg x30', 'sku': 'VTMC500', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('350.00'), 'unit_price': Decimal('520.00'), 'supplier': 'Pharmevo', 'brand': 'Pharmevo', 'status': 'Active'},
    {'product_id': 'PK-1150', 'name': 'Omeprazole 20mg x14', 'sku': 'OMEPZ20', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('260.00'), 'supplier': 'Searle Pakistan', 'brand': 'Searle', 'status': 'Active'},
    {'product_id': 'PK-1151', 'name': 'Antacid 100ml Syrup', 'sku': 'ANTACD', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('145.00'), 'unit_price': Decimal('210.00'), 'supplier': 'Ferozsons', 'brand': 'Ferozsons', 'status': 'Active'},
    {'product_id': 'PK-1152', 'name': 'Cough Syrup 100ml', 'sku': 'CGHSRP', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('165.00'), 'unit_price': Decimal('240.00'), 'supplier': 'GSK Pakistan', 'brand': 'GSK', 'status': 'Active'},
    {'product_id': 'PK-1153', 'name': 'Eye Drops 10ml', 'sku': 'EYEDRP', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'OTC Medicines', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('145.00'), 'unit_price': Decimal('215.00'), 'supplier': 'Alcon Pakistan', 'brand': 'Alcon', 'status': 'Active'},
]
