from decimal import Decimal

# Pharmaceuticals & Health / Personal Care
PERSONAL_CARE_PRODUCTS = [
    {'product_id': 'PK-1162', 'name': 'Head & Shoulders 400ml', 'sku': 'HDSHLD400', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('750.00'), 'unit_price': Decimal('1050.00'), 'supplier': 'P&G Pakistan', 'brand': 'Head&Shoulders', 'status': 'Active'},
    {'product_id': 'PK-1163', 'name': 'Pantene Shampoo 400ml', 'sku': 'PNTN400', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('680.00'), 'unit_price': Decimal('950.00'), 'supplier': 'P&G Pakistan', 'brand': 'Pantene', 'status': 'Active'},
    {'product_id': 'PK-1164', 'name': 'Safeguard Soap 175g', 'sku': 'SFGRD175', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('175.00'), 'supplier': 'P&G Pakistan', 'brand': 'Safeguard', 'status': 'Active'},
    {'product_id': 'PK-1165', 'name': 'Dove Body Wash 400ml', 'sku': 'DVEBW400', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 30, 'reorder_level': 8, 'reorder_qty': 30, 'cost_price': Decimal('680.00'), 'unit_price': Decimal('980.00'), 'supplier': 'Unilever Pakistan', 'brand': 'Dove', 'status': 'Active'},
    {'product_id': 'PK-1166', 'name': 'Colgate Toothpaste 150g', 'sku': 'COLGTP150', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('220.00'), 'unit_price': Decimal('310.00'), 'supplier': 'Colgate Pakistan', 'brand': 'Colgate', 'status': 'Active'},
    {'product_id': 'PK-1167', 'name': 'Close-Up Toothpaste 150g', 'sku': 'CLOSEUP', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('200.00'), 'unit_price': Decimal('290.00'), 'supplier': 'Unilever Pakistan', 'brand': 'Close-Up', 'status': 'Active'},
    {'product_id': 'PK-1168', 'name': 'Gillette Mach3 Blades 4pk', 'sku': 'GLTM34', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('750.00'), 'unit_price': Decimal('1100.00'), 'supplier': 'P&G Pakistan', 'brand': 'Gillette', 'status': 'Active'},
    {'product_id': 'PK-1169', 'name': 'Vaseline Petroleum Jelly 250ml', 'sku': 'VSLN250', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('380.00'), 'unit_price': Decimal('540.00'), 'supplier': 'Unilever Pakistan', 'brand': 'Vaseline', 'status': 'Active'},
    {'product_id': 'PK-1170', 'name': 'Dettol Liquid Soap 250ml', 'sku': 'DTTLSOP', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('320.00'), 'unit_price': Decimal('470.00'), 'supplier': 'Reckitt Pakistan', 'brand': 'Dettol', 'status': 'Active'},
    {'product_id': 'PK-1171', 'name': 'Garnier Face Wash 100ml', 'sku': 'GRNRFW', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Personal Care', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('550.00'), 'unit_price': Decimal('800.00'), 'supplier': "L'Oreal Pakistan", 'brand': 'Garnier', 'status': 'Active'},
]
