from decimal import Decimal

# Pharmaceuticals & Health / Surgical & Medical Supplies
SURGICAL_AND_MEDICAL_SUPPLIES_PRODUCTS = [
    {'product_id': 'PK-1154', 'name': 'Surgical Mask Box 50pcs', 'sku': 'SRGMSK50', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('380.00'), 'unit_price': Decimal('580.00'), 'supplier': 'Local Manufacturer', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1155', 'name': 'Latex Gloves M Box 100', 'sku': 'LTXGLVM', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('550.00'), 'unit_price': Decimal('820.00'), 'supplier': 'Meditech', 'brand': 'Meditech', 'status': 'Active'},
    {'product_id': 'PK-1156', 'name': 'Bandage Roll 5cm', 'sku': 'BNDGRL5', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('85.00'), 'unit_price': Decimal('130.00'), 'supplier': 'Johnson & Johnson', 'brand': 'J&J', 'status': 'Active'},
    {'product_id': 'PK-1157', 'name': 'Antiseptic Dettol 500ml', 'sku': 'DETTOL500', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('380.00'), 'unit_price': Decimal('550.00'), 'supplier': 'Reckitt Pakistan', 'brand': 'Dettol', 'status': 'Active'},
    {'product_id': 'PK-1158', 'name': 'Cotton 100g', 'sku': 'CTTON100', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('180.00'), 'supplier': 'Local Manufacturer', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1159', 'name': 'BP Apparatus Digital', 'sku': 'BPAPD', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 10, 'reorder_level': 3, 'reorder_qty': 10, 'cost_price': Decimal('2800.00'), 'unit_price': Decimal('4200.00'), 'supplier': 'Omron', 'brand': 'Omron', 'status': 'Active'},
    {'product_id': 'PK-1160', 'name': 'Thermometer Digital', 'sku': 'THRMD', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('650.00'), 'unit_price': Decimal('1000.00'), 'supplier': 'Omron', 'brand': 'Omron', 'status': 'Active'},
    {'product_id': 'PK-1161', 'name': 'Glucometer', 'sku': 'GLCMTR', 'unit': 'Unit', 'category': 'Pharmaceuticals & Health', 'subcategory': 'Surgical & Medical Supplies', 'stock_quantity': 10, 'reorder_level': 3, 'reorder_qty': 10, 'cost_price': Decimal('3500.00'), 'unit_price': Decimal('5200.00'), 'supplier': 'Accu-Chek', 'brand': 'Roche', 'status': 'Active'},
]
