from decimal import Decimal

# Automobiles & Accessories / Car Accessories
CAR_ACCESSORIES_PRODUCTS = [
    {'product_id': 'PK-1208', 'name': 'Car Floor Mat Set 5pc', 'sku': 'CFMTS5', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Car Accessories', 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2700.00'), 'supplier': 'Autozone', 'brand': 'Autozone', 'status': 'Active'},
    {'product_id': 'PK-1209', 'name': 'Car Seat Cover Full Set', 'sku': 'CSCSFT', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Car Accessories', 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('2500.00'), 'unit_price': Decimal('3800.00'), 'supplier': 'Autozone', 'brand': 'Autozone', 'status': 'Active'},
    {'product_id': 'PK-1210', 'name': 'Car Charger USB Dual', 'sku': 'CCHRG', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Car Accessories', 'stock_quantity': 50, 'reorder_level': 15, 'reorder_qty': 50, 'cost_price': Decimal('380.00'), 'unit_price': Decimal('600.00'), 'supplier': 'Autozone', 'brand': 'Autozone', 'status': 'Active'},
    {'product_id': 'PK-1211', 'name': 'Air Freshener', 'sku': 'ARFRSH', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Car Accessories', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('290.00'), 'supplier': 'Little Trees', 'brand': 'Little Trees', 'status': 'Active'},
    {'product_id': 'PK-1212', 'name': 'Windshield Wipers Set', 'sku': 'WNSHWP', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Car Accessories', 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('550.00'), 'unit_price': Decimal('850.00'), 'supplier': 'Bosch Pakistan', 'brand': 'Bosch', 'status': 'Active'},
    {'product_id': 'PK-1213', 'name': 'Parking Sensor Kit', 'sku': 'PRKSNS', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Car Accessories', 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2800.00'), 'supplier': 'Local Manufacturer', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1214', 'name': 'Dashcam 1080p', 'sku': 'DSHCM', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Car Accessories', 'stock_quantity': 10, 'reorder_level': 3, 'reorder_qty': 10, 'cost_price': Decimal('5500.00'), 'unit_price': Decimal('8000.00'), 'supplier': 'Xiaomi Pakistan', 'brand': 'Xiaomi', 'status': 'Active'},
]
