from decimal import Decimal

# Automobiles & Accessories / Engine & Maintenance
ENGINE_AND_MAINTENANCE_PRODUCTS = [
    {'product_id': 'PK-1195', 'name': 'Castrol GTX 5W-30 4L', 'sku': 'CSTGTX4L', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('3500.00'), 'unit_price': Decimal('4800.00'), 'supplier': 'Castrol Pakistan', 'brand': 'Castrol', 'status': 'Active'},
    {'product_id': 'PK-1196', 'name': 'Shell Helix 10W-40 4L', 'sku': 'SHHLX4L', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('3200.00'), 'unit_price': Decimal('4500.00'), 'supplier': 'Shell Pakistan', 'brand': 'Shell', 'status': 'Active'},
    {'product_id': 'PK-1197', 'name': 'Total Quartz 5W-40 4L', 'sku': 'TTLQTZ4L', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('3300.00'), 'unit_price': Decimal('4600.00'), 'supplier': 'Total Pakistan', 'brand': 'Total', 'status': 'Active'},
    {'product_id': 'PK-1198', 'name': 'NGK Spark Plug Set 4', 'sku': 'NGKSP4', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('1200.00'), 'unit_price': Decimal('1750.00'), 'supplier': 'NGK Pakistan', 'brand': 'NGK', 'status': 'Active'},
    {'product_id': 'PK-1199', 'name': 'Bosch Oil Filter', 'sku': 'BSCHOFL', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('550.00'), 'unit_price': Decimal('800.00'), 'supplier': 'Bosch Pakistan', 'brand': 'Bosch', 'status': 'Active'},
    {'product_id': 'PK-1200', 'name': 'Air Filter Toyota Corolla', 'sku': 'AFRLYRC', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('650.00'), 'unit_price': Decimal('950.00'), 'supplier': 'Local Compatible', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1201', 'name': 'Coolant 1L', 'sku': 'COOLNT1L', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('380.00'), 'unit_price': Decimal('560.00'), 'supplier': 'Total Pakistan', 'brand': 'Total', 'status': 'Active'},
    {'product_id': 'PK-1202', 'name': 'Brake Fluid DOT4 500ml', 'sku': 'BRFL500', 'unit': 'Unit', 'category': 'Automobiles & Accessories', 'subcategory': 'Engine & Maintenance', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('320.00'), 'unit_price': Decimal('480.00'), 'supplier': 'Shell Pakistan', 'brand': 'Shell', 'status': 'Active'},
]
