from decimal import Decimal

# Grocery & Food Items / Beverages
BEVERAGES_PRODUCTS = [
    {'product_id': 'PK-1057', 'name': 'Nescafé Classic 200g', 'sku': 'NESCF200', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('1350.00'), 'unit_price': Decimal('1750.00'), 'supplier': 'Nestle Pakistan', 'brand': 'Nestle', 'status': 'Active'},
    {'product_id': 'PK-1058', 'name': 'Tapal Danedar 500g', 'sku': 'TAPDN500', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('580.00'), 'unit_price': Decimal('780.00'), 'supplier': 'Tapal Tea', 'brand': 'Tapal', 'status': 'Active'},
    {'product_id': 'PK-1059', 'name': 'Lipton Yellow Label 200g', 'sku': 'LIPYL200', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('650.00'), 'unit_price': Decimal('870.00'), 'supplier': 'Unilever Pakistan', 'brand': 'Lipton', 'status': 'Active'},
    {'product_id': 'PK-1060', 'name': 'Tang Mango 500g', 'sku': 'TNGMNG', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('350.00'), 'unit_price': Decimal('480.00'), 'supplier': 'Mondelez Pak', 'brand': 'Tang', 'status': 'Active'},
    {'product_id': 'PK-1061', 'name': 'Rooh Afza 800ml', 'sku': 'RFAHZA', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('480.00'), 'unit_price': Decimal('630.00'), 'supplier': 'Hamdard', 'brand': 'Hamdard', 'status': 'Active'},
    {'product_id': 'PK-1062', 'name': 'Pepsi 1.5L', 'sku': 'PEPSI15', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 120, 'reorder_level': 30, 'reorder_qty': 120, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('165.00'), 'supplier': 'PepsiCo Pak', 'brand': 'Pepsi', 'status': 'Active'},
    {'product_id': 'PK-1063', 'name': 'Coca-Cola 1.5L', 'sku': 'COKE15', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 120, 'reorder_level': 30, 'reorder_qty': 120, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('165.00'), 'supplier': 'Coca-Cola Pak', 'brand': 'Coca-Cola', 'status': 'Active'},
    {'product_id': 'PK-1064', 'name': 'Minute Maid 1L', 'sku': 'MNJCE1L', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('150.00'), 'unit_price': Decimal('210.00'), 'supplier': 'Coca-Cola Pak', 'brand': 'Minute Maid', 'status': 'Active'},
    {'product_id': 'PK-1065', 'name': 'Olper Milk 1L', 'sku': 'OLPRMK', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 200, 'reorder_level': 40, 'reorder_qty': 200, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('240.00'), 'supplier': 'FrieslandCampina', 'brand': 'Olpers', 'status': 'Active'},
    {'product_id': 'PK-1066', 'name': 'Nurpur Butter 200g', 'sku': 'NURBT200', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Beverages', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('250.00'), 'unit_price': Decimal('340.00'), 'supplier': 'Nurpur Dairy', 'brand': 'Nurpur', 'status': 'Active'},
]
