from decimal import Decimal

# Grocery & Food Items / Dairy & Frozen
DAIRY_AND_FROZEN_PRODUCTS = [
    {'product_id': 'PK-1067', 'name': 'Olpers Full Cream Milk 1L', 'sku': 'OLFCM', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 200, 'reorder_level': 40, 'reorder_qty': 200, 'cost_price': Decimal('185.00'), 'unit_price': Decimal('245.00'), 'supplier': 'FrieslandCampina', 'brand': 'Olpers', 'status': 'Active'},
    {'product_id': 'PK-1068', 'name': 'Nestle Everyday Milk Powder 1kg', 'sku': 'NESEDAY', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('1200.00'), 'unit_price': Decimal('1550.00'), 'supplier': 'Nestle Pakistan', 'brand': 'Nestle', 'status': 'Active'},
    {'product_id': 'PK-1069', 'name': 'Haleeb Milk 1L', 'sku': 'HLBMK', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 200, 'reorder_level': 40, 'reorder_qty': 200, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('240.00'), 'supplier': 'Haleeb Foods', 'brand': 'Haleeb', 'status': 'Active'},
    {'product_id': 'PK-1070', 'name': 'Sapphire Yogurt 1kg', 'sku': 'SAPPYG', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('280.00'), 'unit_price': Decimal('380.00'), 'supplier': 'Sapphire Dairy', 'brand': 'Sapphire', 'status': 'Active'},
    {'product_id': 'PK-1071', 'name': 'Yummy Cheddar Slice 200g', 'sku': 'YUMCHD', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('350.00'), 'unit_price': Decimal('480.00'), 'supplier': 'Dawn Foods', 'brand': 'Yummy', 'status': 'Active'},
    {'product_id': 'PK-1072', 'name': "K&N's Chicken Nuggets 500g", 'sku': 'KNCNG500', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('680.00'), 'unit_price': Decimal('900.00'), 'supplier': 'K&Ns Pakistan', 'brand': "K&N's", 'status': 'Active'},
    {'product_id': 'PK-1073', 'name': "K&N's Chicken Strips 400g", 'sku': 'KNCST400', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('750.00'), 'unit_price': Decimal('980.00'), 'supplier': 'K&Ns Pakistan', 'brand': "K&N's", 'status': 'Active'},
    {'product_id': 'PK-1074', 'name': 'Dawn Croissant 6pcs', 'sku': 'DWNCRS', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Dairy & Frozen', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('280.00'), 'unit_price': Decimal('380.00'), 'supplier': 'Dawn Foods', 'brand': 'Dawn', 'status': 'Active'},
]
