from decimal import Decimal

# Grocery & Food Items / Spices & Condiments
SPICES_AND_CONDIMENTS_PRODUCTS = [
    {'product_id': 'PK-1047', 'name': 'National Biryani Masala 50g', 'sku': 'NBRM50', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('65.00'), 'unit_price': Decimal('95.00'), 'supplier': 'National Foods', 'brand': 'National', 'status': 'Active'},
    {'product_id': 'PK-1048', 'name': 'Shan Biryani Mix 60g', 'sku': 'SHBM60', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('70.00'), 'unit_price': Decimal('100.00'), 'supplier': 'Shan Foods', 'brand': 'Shan', 'status': 'Active'},
    {'product_id': 'PK-1049', 'name': 'Shan Karahi Masala 100g', 'sku': 'SHKR100', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('95.00'), 'unit_price': Decimal('135.00'), 'supplier': 'Shan Foods', 'brand': 'Shan', 'status': 'Active'},
    {'product_id': 'PK-1050', 'name': 'Mehran Nihari Masala', 'sku': 'MEHNM', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('75.00'), 'unit_price': Decimal('110.00'), 'supplier': 'Mehran Foods', 'brand': 'Mehran', 'status': 'Active'},
    {'product_id': 'PK-1051', 'name': 'Turmeric Powder 200g', 'sku': 'TURMRIC', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 100, 'reorder_level': 25, 'reorder_qty': 100, 'cost_price': Decimal('55.00'), 'unit_price': Decimal('80.00'), 'supplier': 'Shan Foods', 'brand': 'Shan', 'status': 'Active'},
    {'product_id': 'PK-1052', 'name': 'Red Chilli Powder 200g', 'sku': 'RCHILLI', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 100, 'reorder_level': 25, 'reorder_qty': 100, 'cost_price': Decimal('65.00'), 'unit_price': Decimal('90.00'), 'supplier': 'Shan Foods', 'brand': 'Shan', 'status': 'Active'},
    {'product_id': 'PK-1053', 'name': 'Garam Masala 100g', 'sku': 'GRAMM', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 100, 'reorder_level': 25, 'reorder_qty': 100, 'cost_price': Decimal('75.00'), 'unit_price': Decimal('105.00'), 'supplier': 'National Foods', 'brand': 'National', 'status': 'Active'},
    {'product_id': 'PK-1054', 'name': 'Cumin Seeds 100g', 'sku': 'CUMN100', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 100, 'reorder_level': 30, 'reorder_qty': 100, 'cost_price': Decimal('50.00'), 'unit_price': Decimal('72.00'), 'supplier': 'Shan Foods', 'brand': 'Shan', 'status': 'Active'},
    {'product_id': 'PK-1055', 'name': 'Black Pepper 50g', 'sku': 'BLKP50', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 100, 'reorder_level': 30, 'reorder_qty': 100, 'cost_price': Decimal('70.00'), 'unit_price': Decimal('100.00'), 'supplier': 'National Foods', 'brand': 'National', 'status': 'Active'},
    {'product_id': 'PK-1056', 'name': 'Coriander Powder 200g', 'sku': 'CORP200', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Spices & Condiments', 'stock_quantity': 100, 'reorder_level': 25, 'reorder_qty': 100, 'cost_price': Decimal('58.00'), 'unit_price': Decimal('84.00'), 'supplier': 'Shan Foods', 'brand': 'Shan', 'status': 'Active'},
]
