from decimal import Decimal

# Grocery & Food Items / Staple Foods
STAPLE_FOODS_PRODUCTS = [
    {'product_id': 'PK-1037', 'name': 'Basmati Rice 25kg', 'sku': 'BSRC25', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('3800.00'), 'unit_price': Decimal('4800.00'), 'supplier': 'Falak Foods', 'brand': 'Falak', 'status': 'Active'},
    {'product_id': 'PK-1038', 'name': 'Basmati Rice 5kg', 'sku': 'BSRC5', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('800.00'), 'unit_price': Decimal('1050.00'), 'supplier': 'Falak Foods', 'brand': 'Falak', 'status': 'Active'},
    {'product_id': 'PK-1039', 'name': 'Wheat Flour Atta 10kg', 'sku': 'ATTA10', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 75, 'reorder_level': 15, 'reorder_qty': 75, 'cost_price': Decimal('1100.00'), 'unit_price': Decimal('1400.00'), 'supplier': 'Sunridge Foods', 'brand': 'Sunridge', 'status': 'Active'},
    {'product_id': 'PK-1040', 'name': 'Wheat Flour Atta 5kg', 'sku': 'ATTA5', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 100, 'reorder_level': 25, 'reorder_qty': 100, 'cost_price': Decimal('580.00'), 'unit_price': Decimal('750.00'), 'supplier': 'Sunridge Foods', 'brand': 'Sunridge', 'status': 'Active'},
    {'product_id': 'PK-1041', 'name': 'Sugar 5kg', 'sku': 'SUGR5', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('600.00'), 'unit_price': Decimal('780.00'), 'supplier': 'National Foods', 'brand': 'National', 'status': 'Active'},
    {'product_id': 'PK-1042', 'name': 'Sugar 1kg', 'sku': 'SUGR1', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 150, 'reorder_level': 30, 'reorder_qty': 150, 'cost_price': Decimal('125.00'), 'unit_price': Decimal('165.00'), 'supplier': 'National Foods', 'brand': 'National', 'status': 'Active'},
    {'product_id': 'PK-1043', 'name': 'Dalda Cooking Oil 5L', 'sku': 'DLDO5', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('2000.00'), 'unit_price': Decimal('2550.00'), 'supplier': 'Dalda Foods', 'brand': 'Dalda', 'status': 'Active'},
    {'product_id': 'PK-1044', 'name': 'Dalda Cooking Oil 1L', 'sku': 'DLDO1', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 120, 'reorder_level': 30, 'reorder_qty': 120, 'cost_price': Decimal('430.00'), 'unit_price': Decimal('560.00'), 'supplier': 'Dalda Foods', 'brand': 'Dalda', 'status': 'Active'},
    {'product_id': 'PK-1045', 'name': 'Sufi Cooking Oil 5L', 'sku': 'SUFO5', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('1900.00'), 'unit_price': Decimal('2450.00'), 'supplier': 'Sufi Foods', 'brand': 'Sufi', 'status': 'Active'},
    {'product_id': 'PK-1046', 'name': 'Canola Oil 3L', 'sku': 'CNLO3', 'unit': 'Unit', 'category': 'Grocery & Food Items', 'subcategory': 'Staple Foods', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('1100.00'), 'unit_price': Decimal('1450.00'), 'supplier': 'Careem Oils', 'brand': 'Careem', 'status': 'Active'},
]
