from decimal import Decimal

# Stationery & Office Supplies / Office Equipment
OFFICE_EQUIPMENT_PRODUCTS = [
    {'product_id': 'PK-1186', 'name': 'Stapler Full Strip', 'sku': 'STPLR', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('650.00'), 'unit_price': Decimal('980.00'), 'supplier': 'Kangaro', 'brand': 'Kangaro', 'status': 'Active'},
    {'product_id': 'PK-1187', 'name': 'Staples Box 1000', 'sku': 'STPLS1K', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('190.00'), 'supplier': 'Kangaro', 'brand': 'Kangaro', 'status': 'Active'},
    {'product_id': 'PK-1188', 'name': 'Hole Punch 2-Hole', 'sku': 'HLPNCH', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('550.00'), 'unit_price': Decimal('830.00'), 'supplier': 'Kangaro', 'brand': 'Kangaro', 'status': 'Active'},
    {'product_id': 'PK-1189', 'name': 'Scissors Large', 'sku': 'SCSSRL', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('280.00'), 'unit_price': Decimal('430.00'), 'supplier': 'Maped', 'brand': 'Maped', 'status': 'Active'},
    {'product_id': 'PK-1190', 'name': 'Tape Dispenser', 'sku': 'TPDSPS', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('380.00'), 'unit_price': Decimal('580.00'), 'supplier': '3M Pakistan', 'brand': '3M', 'status': 'Active'},
    {'product_id': 'PK-1191', 'name': 'File Folder A4', 'sku': 'FLFDR', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('85.00'), 'unit_price': Decimal('135.00'), 'supplier': 'Panda Stationers', 'brand': 'Panda', 'status': 'Active'},
    {'product_id': 'PK-1192', 'name': 'Binder Clip 25mm Box', 'sku': 'BNDCLP25', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('185.00'), 'supplier': 'Local', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1193', 'name': 'Whiteboard Marker Set 4', 'sku': 'WBMKR4', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('250.00'), 'unit_price': Decimal('390.00'), 'supplier': 'Pilot', 'brand': 'Pilot', 'status': 'Active'},
    {'product_id': 'PK-1194', 'name': 'Calculator Scientific', 'sku': 'CALCSC', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Office Equipment', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2700.00'), 'supplier': 'Casio', 'brand': 'Casio', 'status': 'Active'},
]
