from decimal import Decimal

# Stationery & Office Supplies / Paper & Notebooks
PAPER_AND_NOTEBOOKS_PRODUCTS = [
    {'product_id': 'PK-1172', 'name': 'A4 Paper Ream 500 sheets', 'sku': 'A4PRM', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Paper & Notebooks', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('1100.00'), 'unit_price': Decimal('1550.00'), 'supplier': 'Century Paper', 'brand': 'Century', 'status': 'Active'},
    {'product_id': 'PK-1173', 'name': 'Spiral Notebook A4', 'sku': 'SPNBA4', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Paper & Notebooks', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('270.00'), 'supplier': 'Panda Stationers', 'brand': 'Panda', 'status': 'Active'},
    {'product_id': 'PK-1174', 'name': 'Register 200 pages', 'sku': 'REGSTR', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Paper & Notebooks', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('150.00'), 'unit_price': Decimal('225.00'), 'supplier': 'Panda Stationers', 'brand': 'Panda', 'status': 'Active'},
    {'product_id': 'PK-1175', 'name': 'Carbon Copy Book', 'sku': 'CRBNCPBK', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Paper & Notebooks', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('270.00'), 'supplier': 'Panda Stationers', 'brand': 'Panda', 'status': 'Active'},
    {'product_id': 'PK-1176', 'name': 'Graph Paper 100 sheets', 'sku': 'GRPHP100', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Paper & Notebooks', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('380.00'), 'unit_price': Decimal('550.00'), 'supplier': 'Panda Stationers', 'brand': 'Panda', 'status': 'Active'},
    {'product_id': 'PK-1177', 'name': 'Sticky Notes Pad 100', 'sku': 'STKYNTS', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Paper & Notebooks', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('185.00'), 'supplier': '3M Pakistan', 'brand': '3M', 'status': 'Active'},
    {'product_id': 'PK-1178', 'name': 'Envelopes A4 Box 50', 'sku': 'ENVLA4', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Paper & Notebooks', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('320.00'), 'unit_price': Decimal('480.00'), 'supplier': 'Panda Stationers', 'brand': 'Panda', 'status': 'Active'},
]
