from decimal import Decimal

# Stationery & Office Supplies / Writing Instruments
WRITING_INSTRUMENTS_PRODUCTS = [
    {'product_id': 'PK-1179', 'name': 'Camlin Ballpen Box 10', 'sku': 'CMLBP10', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Writing Instruments', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('185.00'), 'supplier': 'Camlin', 'brand': 'Camlin', 'status': 'Active'},
    {'product_id': 'PK-1180', 'name': 'Pilot Ballpen 0.7mm', 'sku': 'PLTBP07', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Writing Instruments', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('45.00'), 'unit_price': Decimal('72.00'), 'supplier': 'Pilot', 'brand': 'Pilot', 'status': 'Active'},
    {'product_id': 'PK-1181', 'name': 'Parker Pen Set', 'sku': 'PARKR', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Writing Instruments', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('1500.00'), 'unit_price': Decimal('2400.00'), 'supplier': 'Parker', 'brand': 'Parker', 'status': 'Active'},
    {'product_id': 'PK-1182', 'name': 'Marker Set 10 colors', 'sku': 'MRKRST10', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Writing Instruments', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('350.00'), 'unit_price': Decimal('540.00'), 'supplier': 'Pilot', 'brand': 'Pilot', 'status': 'Active'},
    {'product_id': 'PK-1183', 'name': 'Highlighter Set 5pcs', 'sku': 'HLGHTST5', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Writing Instruments', 'stock_quantity': 60, 'reorder_level': 15, 'reorder_qty': 60, 'cost_price': Decimal('280.00'), 'unit_price': Decimal('430.00'), 'supplier': 'Staedtler', 'brand': 'Staedtler', 'status': 'Active'},
    {'product_id': 'PK-1184', 'name': 'Pencil HB Box 12', 'sku': 'PNCLHB12', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Writing Instruments', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('280.00'), 'supplier': 'Steadler', 'brand': 'Staedtler', 'status': 'Active'},
    {'product_id': 'PK-1185', 'name': 'Eraser Staedtler x2', 'sku': 'ERSRST', 'unit': 'Unit', 'category': 'Stationery & Office Supplies', 'subcategory': 'Writing Instruments', 'stock_quantity': 100, 'reorder_level': 30, 'reorder_qty': 100, 'cost_price': Decimal('50.00'), 'unit_price': Decimal('80.00'), 'supplier': 'Staedtler', 'brand': 'Staedtler', 'status': 'Active'},
]
