# Generated by Django 4.2.7 on 2026-05-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_supplier_name_company_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchase',
            new_name='purchases_company_e199ae_idx',
            old_name='purchases_company_77b6b4_idx',
        ),
    ]
