# Generated by Django 4.2.7 on 2026-05-22 09:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0003_rename_purchases_company_77b6b4_idx_purchases_company_e199ae_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('quantity_ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL_RECEIVED', 'Partial Received'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('email_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_slips', to='products.product')),
            ],
            options={
                'db_table': 'ordered_slips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ordered_sli_status_b842f1_idx'), models.Index(fields=['email_status'], name='ordered_sli_email_s_3fa94b_idx'), models.Index(fields=['company_name'], name='ordered_sli_company_b0f067_idx'), models.Index(fields=['product'], name='ordered_sli_product_255779_idx')],
            },
        ),
    ]
