# Generated by Django 4.2.7 on 2026-05-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_orderedslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedslip',
            name='email_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
