# Generated by Django 4.2.7 on 2026-05-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_orderedslip_email_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedslip',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
