# Generated by Django 4.2.7 on 2026-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_orderedslip_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedslip',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
