# Generated by Django 4.2.7 on 2026-05-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_suppliercompany'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='suppliercompany',
            new_name='supplier_co_name_387677_idx',
            old_name='purchases_su_name_7a4f7b_idx',
        ),
        migrations.RenameIndex(
            model_name='suppliercompany',
            new_name='supplier_co_categor_b0f53c_idx',
            old_name='purchases_su_catego_2b2a0f_idx',
        ),
    ]
