# Generated by Django 4.2.7 on 2026-07-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_purchaselineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedslip',
            name='delivery_location',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('SHOP', 'Shop')], default='WAREHOUSE', max_length=50),
        ),
    ]
