# Generated by Django 4.2.7 on 2026-05-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_customerreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerreview',
            new_name='insights_cu_created_bfbbba_idx',
            old_name='insights_cus_created_8da17a_idx',
        ),
        migrations.RenameIndex(
            model_name='customerreview',
            new_name='insights_cu_sentime_01dbe4_idx',
            old_name='insights_cus_sentime_57dc94_idx',
        ),
        migrations.RenameIndex(
            model_name='customerreview',
            new_name='insights_cu_rating_b881f1_idx',
            old_name='insights_cus_rating_690d8c_idx',
        ),
    ]
