# Generated by Django 4.2.7 on 2026-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('groq', 'Groq')], max_length=50, unique=True),
        ),
    ]
