# Generated by Django 4.2.7 on 2026-06-07 12:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_apiconfiguration_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique account code (e.g., 1010)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Account name (e.g., Cash, Accounts Receivable)', max_length=100)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], help_text='Root category', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
            ],
            options={
                'db_table': 'accounts_coa_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Transaction date')),
                ('description', models.CharField(help_text='Transaction description', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Reference document or ID', max_length=100, null=True)),
                ('voided', models.BooleanField(default=False, help_text='Whether this transaction has been voided')),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_journal_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'db_table': 'accounts_journal_item',
            },
        ),
        migrations.RemoveIndex(
            model_name='revenue',
            name='screen4_rev_source_c8528f_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card')], default='CASH', help_text='Payment Method', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.CharField(blank=True, help_text='URL or path to receipt image/file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax component', max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance due', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revenue',
            name='category',
            field=models.CharField(choices=[('SALES_REVENUE', 'Sales Revenue'), ('SERVICE_INCOME', 'Service Income'), ('OTHER_INCOME', 'Other Income')], default='SALES_REVENUE', help_text='Revenue Category', max_length=100),
        ),
        migrations.AddField(
            model_name='revenue',
            name='customer',
            field=models.CharField(default='General Customer', help_text='Customer name', max_length=255),
        ),
        migrations.AddField(
            model_name='revenue',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Associated Invoice Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PAID', help_text='Payment status', max_length=50),
        ),
        migrations.AddField(
            model_name='revenue',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total expense amount (inclusive of tax)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='source',
            field=models.CharField(blank=True, help_text='Legacy source / name', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['customer'], name='screen4_rev_custome_9f64c8_idx'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent account for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='accounts.journalentry'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='accounts.journalentry'),
        ),
    ]
