# Generated by Django 4.2.7 on 2026-06-08 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_journalentry_journalitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Invoice date'),
        ),
    ]
