# Generated by Django 4.2.7 on 2026-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('IN', 'Cash Inflow'), ('OUT', 'Cash Outflow')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source_type', models.CharField(choices=[('sale', 'Sale'), ('expense', 'Expense'), ('purchase', 'Purchase'), ('other', 'Other')], default='other', max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cash_transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['txn_type', 'date'], name='cash_transa_txn_typ_37c4bc_idx'), models.Index(fields=['source_type', 'source_id'], name='cash_transa_source__1734fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Model name: Sale, Expense, Product, etc.', max_length=100)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(help_text='CREATE, UPDATE, DELETE, VOID', max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, default='system', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity__c2633a_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx')],
            },
        ),
    ]
