# Generated by Django 4.2.7 on 2026-06-16 18:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cashtransaction_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PAYROLL', 'Payroll'), ('MARKETING', 'Marketing'), ('RENT_UTILITIES', 'Rent & Utilities'), ('SUPPLIES', 'Supplies'), ('TECHNOLOGY', 'Technology'), ('TRAVEL', 'Travel'), ('OTHER', 'Other'), ('ALL', 'All Categories (Total)')], help_text='Expense category this budget applies to', max_length=50)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', help_text='Budget period type', max_length=20)),
                ('year', models.IntegerField(help_text='Budget year (e.g. 2026)')),
                ('month', models.IntegerField(blank=True, help_text='Budget month (1-12). Null for quarterly/annual budgets.', null=True)),
                ('quarter', models.IntegerField(blank=True, help_text='Budget quarter (1-4). Null for monthly/annual budgets.', null=True)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, help_text='Planned budget for this period', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('department', models.CharField(blank=True, help_text='Optional: restrict budget to a specific department', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Budget',
                'verbose_name_plural': 'Expense Budgets',
                'db_table': 'expense_budgets',
                'ordering': ['-year', '-month', 'category'],
                'indexes': [models.Index(fields=['year', 'month', 'category'], name='expense_bud_year_03debb_idx'), models.Index(fields=['year', 'quarter', 'category'], name='expense_bud_year_1515d8_idx')],
                'unique_together': {('category', 'period_type', 'year', 'month', 'quarter', 'department')},
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this instalment', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(help_text='Date payment was received')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Bank reference, cheque number, etc.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is against', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'db_table': 'invoice_payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice', '-payment_date'], name='invoice_pay_invoice_d9632d_idx')],
            },
        ),
    ]
