# Generated by Django 4.2.7 on 2026-06-21 08:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0008_add_expense_budget_invoice_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('RENT', 'Rent'), ('SUBSCRIPTION', 'Software Subscription'), ('MARKETING_CAMPAIGN', 'Marketing/Ads Campaign'), ('MAINTENANCE', 'Office Maintenance'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other Operating Cost')], default='RENT', max_length=50)),
                ('name', models.CharField(help_text='Name of the cost (e.g., Office Rent, Adobe Creative Suite)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField(help_text='Due date for payment')),
                ('payment_date', models.DateField(blank=True, help_text='Date when cost was paid', null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card')], default='BANK_TRANSFER', max_length=50)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recurring_operational_costs',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas'), ('INTERNET', 'Internet/Phone'), ('OTHER', 'Other Utilities')], default='ELECTRICITY', max_length=50)),
                ('bill_number', models.CharField(blank=True, help_text='Bill reference/invoice number', max_length=100, null=True)),
                ('billing_period_start', models.DateField(blank=True, help_text='Billing period start date', null=True)),
                ('billing_period_end', models.DateField(blank=True, help_text='Billing period end date', null=True)),
                ('due_date', models.DateField(help_text='Due date for payment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bill amount (inclusive of taxes)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax component in the bill', max_digits=15)),
                ('payment_date', models.DateField(blank=True, help_text='Date when bill was paid', null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card')], default='CASH', max_length=50)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt', models.CharField(blank=True, help_text='Link or path to bill receipt/document', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'utility_bills',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='expense',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata JSON for specific expense details', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base/Net salary amount paid', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pay_period_start', models.DateField(help_text='Start date of pay period')),
                ('pay_period_end', models.DateField(help_text='End date of pay period')),
                ('payment_date', models.DateField(blank=True, help_text='Date when salary was paid', null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card')], default='BANK_TRANSFER', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee receiving the salary', on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary_payments',
                'ordering': ['-pay_period_end', '-created_at'],
            },
        ),
    ]
