# Generated by Django 4.2.7 on 2026-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_recurringcost_utilitybill_expense_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('PAYROLL', 'Payroll'), ('MARKETING', 'Marketing'), ('RENT_UTILITIES', 'Rent & Utilities'), ('SUPPLIES', 'Supplies'), ('TECHNOLOGY', 'Technology'), ('TRAVEL', 'Travel'), ('WAREHOUSE', 'Warehouse Expenses'), ('OTHER', 'Other')], help_text='Expense category', max_length=50),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='category',
            field=models.CharField(choices=[('PAYROLL', 'Payroll'), ('MARKETING', 'Marketing'), ('RENT_UTILITIES', 'Rent & Utilities'), ('SUPPLIES', 'Supplies'), ('TECHNOLOGY', 'Technology'), ('TRAVEL', 'Travel'), ('WAREHOUSE', 'Warehouse Expenses'), ('OTHER', 'Other'), ('ALL', 'All Categories (Total)')], help_text='Expense category this budget applies to', max_length=50),
        ),
    ]
