"""Auto-generated aggregated products module"""
from decimal import Decimal

from product_catalog.electronics_and_appliances.mobile_phones import MOBILE_PHONES_PRODUCTS
from product_catalog.electronics_and_appliances.laptops_and_computers import LAPTOPS_AND_COMPUTERS_PRODUCTS
from product_catalog.electronics_and_appliances.televisions import TELEVISIONS_PRODUCTS
from product_catalog.electronics_and_appliances.home_appliances import HOME_APPLIANCES_PRODUCTS
from product_catalog.grocery_and_food_items.staple_foods import STAPLE_FOODS_PRODUCTS
from product_catalog.grocery_and_food_items.spices_and_condiments import SPICES_AND_CONDIMENTS_PRODUCTS
from product_catalog.grocery_and_food_items.beverages import BEVERAGES_PRODUCTS
from product_catalog.grocery_and_food_items.dairy_and_frozen import DAIRY_AND_FROZEN_PRODUCTS
from product_catalog.clothing_and_textiles.mens_wear import MENS_WEAR_PRODUCTS
from product_catalog.clothing_and_textiles.womens_wear import WOMENS_WEAR_PRODUCTS
from product_catalog.clothing_and_textiles.footwear import FOOTWEAR_PRODUCTS
from product_catalog.clothing_and_textiles.fabric_and_accessories import FABRIC_AND_ACCESSORIES_PRODUCTS
from product_catalog.pharmaceuticals_and_health.otc_medicines import OTC_MEDICINES_PRODUCTS
from product_catalog.pharmaceuticals_and_health.surgical_and_medical_supplies import SURGICAL_AND_MEDICAL_SUPPLIES_PRODUCTS
from product_catalog.pharmaceuticals_and_health.personal_care import PERSONAL_CARE_PRODUCTS
from product_catalog.stationery_and_office_supplies.paper_and_notebooks import PAPER_AND_NOTEBOOKS_PRODUCTS
from product_catalog.stationery_and_office_supplies.writing_instruments import WRITING_INSTRUMENTS_PRODUCTS
from product_catalog.stationery_and_office_supplies.office_equipment import OFFICE_EQUIPMENT_PRODUCTS

ALL_PRODUCTS = []
ALL_PRODUCTS += MOBILE_PHONES_PRODUCTS
ALL_PRODUCTS += LAPTOPS_AND_COMPUTERS_PRODUCTS
ALL_PRODUCTS += TELEVISIONS_PRODUCTS
ALL_PRODUCTS += HOME_APPLIANCES_PRODUCTS
ALL_PRODUCTS += STAPLE_FOODS_PRODUCTS
ALL_PRODUCTS += SPICES_AND_CONDIMENTS_PRODUCTS
ALL_PRODUCTS += BEVERAGES_PRODUCTS
ALL_PRODUCTS += DAIRY_AND_FROZEN_PRODUCTS
ALL_PRODUCTS += MENS_WEAR_PRODUCTS
ALL_PRODUCTS += WOMENS_WEAR_PRODUCTS
ALL_PRODUCTS += FOOTWEAR_PRODUCTS
ALL_PRODUCTS += FABRIC_AND_ACCESSORIES_PRODUCTS
ALL_PRODUCTS += OTC_MEDICINES_PRODUCTS
ALL_PRODUCTS += SURGICAL_AND_MEDICAL_SUPPLIES_PRODUCTS
ALL_PRODUCTS += PERSONAL_CARE_PRODUCTS
ALL_PRODUCTS += PAPER_AND_NOTEBOOKS_PRODUCTS
ALL_PRODUCTS += WRITING_INSTRUMENTS_PRODUCTS
ALL_PRODUCTS += OFFICE_EQUIPMENT_PRODUCTS

