# Use node image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY . .

# Expose Vite dev port
EXPOSE 5173

# Run the server on 0.0.0.0 so host can access it
CMD ["npm", "run", "dev", "--", "--host"]
