from decimal import Decimal

# Construction & Hardware / Cement & Building Materials
CEMENT_AND_BUILDING_MATERIALS_PRODUCTS = [
    {'product_id': 'PK-1111', 'name': 'DG Khan Cement 50kg', 'sku': 'DGKCEM', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 200, 'reorder_level': 50, 'reorder_qty': 200, 'cost_price': Decimal('850.00'), 'unit_price': Decimal('1050.00'), 'supplier': 'DG Khan Cement', 'brand': 'DG Khan', 'status': 'Active'},
    {'product_id': 'PK-1112', 'name': 'Lucky Cement 50kg', 'sku': 'LKCEM', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 200, 'reorder_level': 50, 'reorder_qty': 200, 'cost_price': Decimal('840.00'), 'unit_price': Decimal('1040.00'), 'supplier': 'Lucky Cement', 'brand': 'Lucky', 'status': 'Active'},
    {'product_id': 'PK-1113', 'name': 'Maple Leaf Cement 50kg', 'sku': 'MLCEM', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 200, 'reorder_level': 50, 'reorder_qty': 200, 'cost_price': Decimal('845.00'), 'unit_price': Decimal('1045.00'), 'supplier': 'Maple Leaf', 'brand': 'Maple Leaf', 'status': 'Active'},
    {'product_id': 'PK-1114', 'name': 'Red Brick (per 1000)', 'sku': 'RDBRIK', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('14000.00'), 'unit_price': Decimal('18000.00'), 'supplier': 'Local Kilns', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1115', 'name': 'Block 6 inch (per piece)', 'sku': 'BLK6', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('55.00'), 'unit_price': Decimal('80.00'), 'supplier': 'Local Manufacturer', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1116', 'name': 'River Sand per cubic ft', 'sku': 'RVSND', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('250.00'), 'supplier': 'Al-Noor Aggregates', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1117', 'name': 'Crush Stone per cubic ft', 'sku': 'CRSHST', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('200.00'), 'unit_price': Decimal('280.00'), 'supplier': 'Al-Noor Aggregates', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1118', 'name': 'Steel Rod 10mm per kg', 'sku': 'STLRD10', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Cement & Building Materials', 'stock_quantity': 500, 'reorder_level': 100, 'reorder_qty': 500, 'cost_price': Decimal('260.00'), 'unit_price': Decimal('320.00'), 'supplier': 'Amreli Steels', 'brand': 'Amreli', 'status': 'Active'},
]
