from decimal import Decimal

# Construction & Hardware / Paints & Finishes
PAINTS_AND_FINISHES_PRODUCTS = [
    {'product_id': 'PK-1119', 'name': 'ICI Dulux Weathershield 4L', 'sku': 'ICIDWX4', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Paints & Finishes', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('3800.00'), 'unit_price': Decimal('5000.00'), 'supplier': 'ICI Pakistan', 'brand': 'ICI Dulux', 'status': 'Active'},
    {'product_id': 'PK-1120', 'name': 'ICI Dulux Interior 4L', 'sku': 'ICIDIN4', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Paints & Finishes', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('2800.00'), 'unit_price': Decimal('3800.00'), 'supplier': 'ICI Pakistan', 'brand': 'ICI Dulux', 'status': 'Active'},
    {'product_id': 'PK-1121', 'name': 'Berger WeatherCoat 4L', 'sku': 'BRGWC4', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Paints & Finishes', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('3600.00'), 'unit_price': Decimal('4800.00'), 'supplier': 'Berger Paints', 'brand': 'Berger', 'status': 'Active'},
    {'product_id': 'PK-1122', 'name': 'Nippon Paint 4L', 'sku': 'NIPN4', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Paints & Finishes', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('3200.00'), 'unit_price': Decimal('4400.00'), 'supplier': 'Nippon Paint', 'brand': 'Nippon', 'status': 'Active'},
    {'product_id': 'PK-1123', 'name': 'Wall Putty 20kg', 'sku': 'WLPTY20', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Paints & Finishes', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('1200.00'), 'unit_price': Decimal('1600.00'), 'supplier': 'Asian Paints', 'brand': 'Asian', 'status': 'Active'},
    {'product_id': 'PK-1124', 'name': 'Primer 4L', 'sku': 'PRMR4', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Paints & Finishes', 'stock_quantity': 30, 'reorder_level': 8, 'reorder_qty': 30, 'cost_price': Decimal('1500.00'), 'unit_price': Decimal('2100.00'), 'supplier': 'ICI Pakistan', 'brand': 'ICI', 'status': 'Active'},
    {'product_id': 'PK-1125', 'name': 'Enamel Paint 1L', 'sku': 'ENMPNT1', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Paints & Finishes', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('750.00'), 'unit_price': Decimal('1050.00'), 'supplier': 'Berger Paints', 'brand': 'Berger', 'status': 'Active'},
]
