from decimal import Decimal

# Construction & Hardware / Plumbing & Electrical
PLUMBING_AND_ELECTRICAL_PRODUCTS = [
    {'product_id': 'PK-1126', 'name': 'CPVC Pipe 1/2 inch', 'sku': 'CPVCP12', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('250.00'), 'supplier': 'Supreme Pipes', 'brand': 'Supreme', 'status': 'Active'},
    {'product_id': 'PK-1127', 'name': 'CPVC Pipe 3/4 inch', 'sku': 'CPVCP34', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('250.00'), 'unit_price': Decimal('340.00'), 'supplier': 'Supreme Pipes', 'brand': 'Supreme', 'status': 'Active'},
    {'product_id': 'PK-1128', 'name': 'Ball Valve 1/2 inch', 'sku': 'BLVLV12', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('220.00'), 'unit_price': Decimal('320.00'), 'supplier': 'Local Manufacturer', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1129', 'name': 'Water Pump 0.5HP', 'sku': 'WTPMP05', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 10, 'reorder_level': 3, 'reorder_qty': 10, 'cost_price': Decimal('12000.00'), 'unit_price': Decimal('16000.00'), 'supplier': 'Siemens Pakistan', 'brand': 'Siemens', 'status': 'Active'},
    {'product_id': 'PK-1130', 'name': 'Electric Wire 2.5mm (per m)', 'sku': 'EWIRE25', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 200, 'reorder_level': 50, 'reorder_qty': 200, 'cost_price': Decimal('45.00'), 'unit_price': Decimal('65.00'), 'supplier': 'Pakistan Cables', 'brand': 'Pak Cables', 'status': 'Active'},
    {'product_id': 'PK-1131', 'name': 'Electric Wire 4mm (per m)', 'sku': 'EWIRE4', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 200, 'reorder_level': 50, 'reorder_qty': 200, 'cost_price': Decimal('65.00'), 'unit_price': Decimal('95.00'), 'supplier': 'Pakistan Cables', 'brand': 'Pak Cables', 'status': 'Active'},
    {'product_id': 'PK-1132', 'name': 'MCB 20A Single', 'sku': 'MCB20S', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 80, 'reorder_level': 20, 'reorder_qty': 80, 'cost_price': Decimal('450.00'), 'unit_price': Decimal('650.00'), 'supplier': 'Siemens Pakistan', 'brand': 'Siemens', 'status': 'Active'},
    {'product_id': 'PK-1133', 'name': 'LED Downlight 7W', 'sku': 'LEDDN7', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('180.00'), 'unit_price': Decimal('280.00'), 'supplier': 'Philips Pakistan', 'brand': 'Philips', 'status': 'Active'},
    {'product_id': 'PK-1134', 'name': 'LED Bulb 12W', 'sku': 'LEDBL12', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 150, 'reorder_level': 30, 'reorder_qty': 150, 'cost_price': Decimal('120.00'), 'unit_price': Decimal('190.00'), 'supplier': 'Philips Pakistan', 'brand': 'Philips', 'status': 'Active'},
    {'product_id': 'PK-1135', 'name': 'Fan Ceiling 56"', 'sku': 'FANC56', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Plumbing & Electrical', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('3200.00'), 'unit_price': Decimal('4500.00'), 'supplier': 'GFC Fans', 'brand': 'GFC', 'status': 'Active'},
]
