from decimal import Decimal

# Construction & Hardware / Tools & Hardware
TOOLS_AND_HARDWARE_PRODUCTS = [
    {'product_id': 'PK-1136', 'name': 'Stanley Hammer', 'sku': 'STLHMR', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('850.00'), 'unit_price': Decimal('1200.00'), 'supplier': 'Stanley Tools', 'brand': 'Stanley', 'status': 'Active'},
    {'product_id': 'PK-1137', 'name': 'Drill Machine 13mm', 'sku': 'DRLM13', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 10, 'reorder_level': 3, 'reorder_qty': 10, 'cost_price': Decimal('4500.00'), 'unit_price': Decimal('6200.00'), 'supplier': 'Bosch Pakistan', 'brand': 'Bosch', 'status': 'Active'},
    {'product_id': 'PK-1138', 'name': 'Measuring Tape 5m', 'sku': 'MSTPE5', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('350.00'), 'unit_price': Decimal('520.00'), 'supplier': 'Stanley Tools', 'brand': 'Stanley', 'status': 'Active'},
    {'product_id': 'PK-1139', 'name': 'Screw Set 100pcs', 'sku': 'SCRWST', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('450.00'), 'unit_price': Decimal('680.00'), 'supplier': 'Local Manufacturer', 'brand': 'Local', 'status': 'Active'},
    {'product_id': 'PK-1140', 'name': 'Wrench Set 8pcs', 'sku': 'WRNCH8', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2600.00'), 'supplier': 'Stanley Tools', 'brand': 'Stanley', 'status': 'Active'},
    {'product_id': 'PK-1141', 'name': 'Paint Brush Set 5pcs', 'sku': 'PNTBRSH5', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('600.00'), 'unit_price': Decimal('900.00'), 'supplier': 'Berger Paints', 'brand': 'Berger', 'status': 'Active'},
    {'product_id': 'PK-1142', 'name': 'Safety Gloves', 'sku': 'SFGLV', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 50, 'reorder_level': 10, 'reorder_qty': 50, 'cost_price': Decimal('280.00'), 'unit_price': Decimal('420.00'), 'supplier': '3M Pakistan', 'brand': '3M', 'status': 'Active'},
    {'product_id': 'PK-1143', 'name': 'Safety Helmet', 'sku': 'SFHLMT', 'unit': 'Unit', 'category': 'Construction & Hardware', 'subcategory': 'Tools & Hardware', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('450.00'), 'unit_price': Decimal('680.00'), 'supplier': '3M Pakistan', 'brand': '3M', 'status': 'Active'},
]
