from decimal import Decimal

# Clothing & Textiles / Fabric & Accessories
FABRIC_AND_ACCESSORIES_PRODUCTS = [
    {'product_id': 'PK-1103', 'name': 'Lawn Fabric per meter', 'sku': 'LWNFBR', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('250.00'), 'unit_price': Decimal('380.00'), 'supplier': 'Gul Ahmed', 'brand': 'Gul Ahmed', 'status': 'Active'},
    {'product_id': 'PK-1104', 'name': 'Chiffon Fabric per meter', 'sku': 'CHFFN', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('350.00'), 'unit_price': Decimal('520.00'), 'supplier': 'Nishat', 'brand': 'Nishat', 'status': 'Active'},
    {'product_id': 'PK-1105', 'name': 'Cotton Fabric per meter', 'sku': 'CTNFBR', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 100, 'reorder_level': 20, 'reorder_qty': 100, 'cost_price': Decimal('200.00'), 'unit_price': Decimal('310.00'), 'supplier': 'Al-Karam', 'brand': 'Al-Karam', 'status': 'Active'},
    {'product_id': 'PK-1106', 'name': 'Silk Fabric per meter', 'sku': 'SLKFBR', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 40, 'reorder_level': 10, 'reorder_qty': 40, 'cost_price': Decimal('700.00'), 'unit_price': Decimal('1050.00'), 'supplier': 'Khaadi', 'brand': 'Khaadi', 'status': 'Active'},
    {'product_id': 'PK-1107', 'name': 'Ladies Handbag', 'sku': 'LHDBG', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('1200.00'), 'unit_price': Decimal('1900.00'), 'supplier': 'Insignia', 'brand': 'Insignia', 'status': 'Active'},
    {'product_id': 'PK-1108', 'name': 'Men Leather Belt', 'sku': 'MLBLT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('600.00'), 'unit_price': Decimal('950.00'), 'supplier': 'Bata Pakistan', 'brand': 'Bata', 'status': 'Active'},
    {'product_id': 'PK-1109', 'name': 'Ladies Scarf', 'sku': 'LDSCRF', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 60, 'reorder_level': 20, 'reorder_qty': 60, 'cost_price': Decimal('400.00'), 'unit_price': Decimal('650.00'), 'supplier': 'Sapphire', 'brand': 'Sapphire', 'status': 'Active'},
    {'product_id': 'PK-1110', 'name': 'Men Necktie', 'sku': 'MNTIE', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Fabric & Accessories', 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('550.00'), 'unit_price': Decimal('900.00'), 'supplier': 'Almirah', 'brand': 'Almirah', 'status': 'Active'},
]
