from decimal import Decimal

# Clothing & Textiles / Footwear
FOOTWEAR_PRODUCTS = [
    {'product_id': 'PK-1095', 'name': 'Bata Men Leather Shoes', 'sku': 'BATMS', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('3500.00'), 'unit_price': Decimal('5200.00'), 'supplier': 'Bata Pakistan', 'brand': 'Bata', 'status': 'Active'},
    {'product_id': 'PK-1096', 'name': 'Bata Women Pumps', 'sku': 'BATWS', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('2800.00'), 'unit_price': Decimal('4200.00'), 'supplier': 'Bata Pakistan', 'brand': 'Bata', 'status': 'Active'},
    {'product_id': 'PK-1097', 'name': 'Servis Men Sandals', 'sku': 'SRVMS', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 20, 'reorder_level': 10, 'reorder_qty': 20, 'cost_price': Decimal('1200.00'), 'unit_price': Decimal('1900.00'), 'supplier': 'Servis', 'brand': 'Servis', 'status': 'Active'},
    {'product_id': 'PK-1098', 'name': 'Servis School Shoes', 'sku': 'SRVSS', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 20, 'reorder_level': 8, 'reorder_qty': 20, 'cost_price': Decimal('1500.00'), 'unit_price': Decimal('2300.00'), 'supplier': 'Servis', 'brand': 'Servis', 'status': 'Active'},
    {'product_id': 'PK-1099', 'name': 'Nike Air Max (Replica)', 'sku': 'NKAM', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 10, 'reorder_level': 5, 'reorder_qty': 10, 'cost_price': Decimal('3800.00'), 'unit_price': Decimal('6000.00'), 'supplier': 'Sports World', 'brand': 'Nike', 'status': 'Active'},
    {'product_id': 'PK-1100', 'name': 'Stylo Women Heels', 'sku': 'STYWH', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('2200.00'), 'unit_price': Decimal('3400.00'), 'supplier': 'Stylo', 'brand': 'Stylo', 'status': 'Active'},
    {'product_id': 'PK-1101', 'name': 'Metro Men Casual', 'sku': 'MTRMC', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 20, 'reorder_level': 8, 'reorder_qty': 20, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2800.00'), 'supplier': 'Metro Shoes', 'brand': 'Metro', 'status': 'Active'},
    {'product_id': 'PK-1102', 'name': 'Hush Puppies Loafers', 'sku': 'HPLF', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': 'Footwear', 'stock_quantity': 10, 'reorder_level': 5, 'reorder_qty': 10, 'cost_price': Decimal('4200.00'), 'unit_price': Decimal('6500.00'), 'supplier': 'Hush Puppies', 'brand': 'Hush Puppies', 'status': 'Active'},
]
