from decimal import Decimal

# Clothing & Textiles / Men's Wear
MENS_WEAR_PRODUCTS = [
    {'product_id': 'PK-1075', 'name': 'Gul Ahmed Lawn Suit 3pc', 'sku': 'GALWN3', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('1200.00'), 'unit_price': Decimal('1800.00'), 'supplier': 'Gul Ahmed', 'brand': 'Gul Ahmed', 'status': 'Active'},
    {'product_id': 'PK-1076', 'name': 'Almirah Men Kurta', 'sku': 'ALMKRT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('1500.00'), 'unit_price': Decimal('2200.00'), 'supplier': 'Almirah', 'brand': 'Almirah', 'status': 'Active'},
    {'product_id': 'PK-1077', 'name': 'Khaadi Men Shalwar Kameez', 'sku': 'KHDSK', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('2500.00'), 'unit_price': Decimal('3800.00'), 'supplier': 'Khaadi', 'brand': 'Khaadi', 'status': 'Active'},
    {'product_id': 'PK-1078', 'name': 'J. Men Shirt', 'sku': 'JMSHRT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2700.00'), 'supplier': 'J. (Junaid Jamshed)', 'brand': 'J.', 'status': 'Active'},
    {'product_id': 'PK-1079', 'name': 'Bonanza Men Sweater', 'sku': 'BNSSWT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 20, 'reorder_level': 5, 'reorder_qty': 20, 'cost_price': Decimal('2200.00'), 'unit_price': Decimal('3200.00'), 'supplier': 'Bonanza Satrangi', 'brand': 'Bonanza', 'status': 'Active'},
    {'product_id': 'PK-1080', 'name': 'Men Denim Jeans 32', 'sku': 'MDNJNS32', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('1400.00'), 'unit_price': Decimal('2100.00'), 'supplier': 'Outfitters', 'brand': 'Outfitters', 'status': 'Active'},
    {'product_id': 'PK-1081', 'name': 'Men Denim Jeans 34', 'sku': 'MDNJNS34', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('1400.00'), 'unit_price': Decimal('2100.00'), 'supplier': 'Outfitters', 'brand': 'Outfitters', 'status': 'Active'},
    {'product_id': 'PK-1082', 'name': 'Men Formal Trouser', 'sku': 'MFRTRS', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 30, 'reorder_level': 10, 'reorder_qty': 30, 'cost_price': Decimal('1600.00'), 'unit_price': Decimal('2400.00'), 'supplier': 'Sana Safinaz', 'brand': 'Sana Safinaz', 'status': 'Active'},
    {'product_id': 'PK-1083', 'name': 'Men Polo T-Shirt', 'sku': 'MPTSHRT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 40, 'reorder_level': 15, 'reorder_qty': 40, 'cost_price': Decimal('650.00'), 'unit_price': Decimal('1000.00'), 'supplier': 'Breakout', 'brand': 'Breakout', 'status': 'Active'},
    {'product_id': 'PK-1084', 'name': 'Men Sports Shorts', 'sku': 'MSPSHRT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Men's Wear", 'stock_quantity': 40, 'reorder_level': 15, 'reorder_qty': 40, 'cost_price': Decimal('700.00'), 'unit_price': Decimal('1100.00'), 'supplier': 'Breakout', 'brand': 'Breakout', 'status': 'Active'},
]
