from decimal import Decimal

# Clothing & Textiles / Women's Wear
WOMENS_WEAR_PRODUCTS = [
    {'product_id': 'PK-1085', 'name': 'Gul Ahmed Summer Collection 3pc', 'sku': 'GALSC3', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 25, 'reorder_level': 10, 'reorder_qty': 25, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2800.00'), 'supplier': 'Gul Ahmed', 'brand': 'Gul Ahmed', 'status': 'Active'},
    {'product_id': 'PK-1086', 'name': 'Sana Safinaz Ready-to-Wear', 'sku': 'SNSFRTW', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 15, 'reorder_level': 5, 'reorder_qty': 15, 'cost_price': Decimal('4500.00'), 'unit_price': Decimal('6800.00'), 'supplier': 'Sana Safinaz', 'brand': 'Sana Safinaz', 'status': 'Active'},
    {'product_id': 'PK-1087', 'name': 'Khaadi Pret Kurta', 'sku': 'KHDPRTKRT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 20, 'reorder_level': 8, 'reorder_qty': 20, 'cost_price': Decimal('2200.00'), 'unit_price': Decimal('3400.00'), 'supplier': 'Khaadi', 'brand': 'Khaadi', 'status': 'Active'},
    {'product_id': 'PK-1088', 'name': 'Maria B Lawn 3pc', 'sku': 'MBLWN3', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 20, 'reorder_level': 8, 'reorder_qty': 20, 'cost_price': Decimal('3200.00'), 'unit_price': Decimal('5000.00'), 'supplier': 'Maria B', 'brand': 'Maria B', 'status': 'Active'},
    {'product_id': 'PK-1089', 'name': 'Nishat Linen Suit', 'sku': 'NSHLNN', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 20, 'reorder_level': 8, 'reorder_qty': 20, 'cost_price': Decimal('2800.00'), 'unit_price': Decimal('4200.00'), 'supplier': 'Nishat Linen', 'brand': 'Nishat', 'status': 'Active'},
    {'product_id': 'PK-1090', 'name': 'Zellbury Kurta Set', 'sku': 'ZLBKRT', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 25, 'reorder_level': 10, 'reorder_qty': 25, 'cost_price': Decimal('1500.00'), 'unit_price': Decimal('2300.00'), 'supplier': 'Zellbury', 'brand': 'Zellbury', 'status': 'Active'},
    {'product_id': 'PK-1091', 'name': 'Women Capri Pants', 'sku': 'WCPRI', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 40, 'reorder_level': 15, 'reorder_qty': 40, 'cost_price': Decimal('800.00'), 'unit_price': Decimal('1250.00'), 'supplier': 'Edenrobe', 'brand': 'Edenrobe', 'status': 'Active'},
    {'product_id': 'PK-1092', 'name': 'Women Cardigan', 'sku': 'WCRDGN', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 25, 'reorder_level': 10, 'reorder_qty': 25, 'cost_price': Decimal('1500.00'), 'unit_price': Decimal('2400.00'), 'supplier': 'Bonanza Satrangi', 'brand': 'Bonanza', 'status': 'Active'},
    {'product_id': 'PK-1093', 'name': 'Women Abaya Plain', 'sku': 'WABPLN', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 20, 'reorder_level': 8, 'reorder_qty': 20, 'cost_price': Decimal('1800.00'), 'unit_price': Decimal('2700.00'), 'supplier': 'Al-Karam', 'brand': 'Al-Karam', 'status': 'Active'},
    {'product_id': 'PK-1094', 'name': 'Women Dupatta Lawn', 'sku': 'WDPLWN', 'unit': 'Unit', 'category': 'Clothing & Textiles', 'subcategory': "Women's Wear", 'stock_quantity': 60, 'reorder_level': 20, 'reorder_qty': 60, 'cost_price': Decimal('500.00'), 'unit_price': Decimal('800.00'), 'supplier': 'Gul Ahmed', 'brand': 'Gul Ahmed', 'status': 'Active'},
]
