# Generated by Django 4.2.7 on 2026-06-09 16:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_discount_alter_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
