# Generated by Django 4.2.7 on 2026-06-16 18:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_inventorytransaction'),
        ('sales', '0004_sale_unit_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('return_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
            options={
                'db_table': 'sales_returns',
                'ordering': ['-return_date', '-created_at'],
                'indexes': [models.Index(fields=['return_date'], name='sales_retur_return__6cb693_idx'), models.Index(fields=['sale'], name='sales_retur_sale_id_0cf4fa_idx'), models.Index(fields=['product'], name='sales_retur_product_f74e05_idx')],
            },
        ),
    ]
