# Generated by Django 4.2.7 on 2026-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salereturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
