# Generated by Django 4.2.7 on 2026-06-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment')], help_text='Direction of stock movement', max_length=20)),
                ('quantity', models.IntegerField(help_text='Always positive; txn_type determines direction')),
                ('reference_type', models.CharField(blank=True, default='', help_text='Source: sale, purchase, opening_stock, adjustment', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='FK to source record (Sale.id, Purchase.id, etc.)', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.product')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['product', 'date'], name='inventory_t_product_bdc5c3_idx'), models.Index(fields=['txn_type'], name='inventory_t_txn_typ_f6e971_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_t_referen_ef9dcf_idx')],
            },
        ),
    ]
