# Generated by Django 4.2.7 on 2026-07-07 17:00

import django.core.validators
from django.db import migrations, models


def populate_shop_warehouse_stock(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for p in Product.objects.all():
        total = p.stock_quantity
        if total <= 0:
            shop = 0
        elif total > 150:
            shop = 70
        elif total >= 100:
            shop = 50
        elif total >= 50:
            shop = 40
        else:
            shop = min(total, 20)
        
        warehouse = max(0, total - shop)
        p.shop_stock = shop
        p.warehouse_stock = warehouse
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_bulkproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop_stock'], name='products_shop_st_d0bc11_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['warehouse_stock'], name='products_warehou_ef4b2e_idx'),
        ),
        migrations.RunPython(populate_shop_warehouse_stock, reverse_code=migrations.RunPython.noop),
    ]
